package co.simplon.glucidenfoliebusiness.entities;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

//visibilté publi visible de n'importe ou donc pas de public
//abstract = absence de mot clé public 
@MappedSuperclass // cette classe contient des éléments de mapping
abstract class AbstractEntity {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Long id;

	protected AbstractEntity() {

	}

	public Long getId() {
		return id;
	}

	// ID generated by DB
	public void setId(Long id) {
		this.id = id;
	}

}
